"""
Attribute lexicon: SUNCG room category -> semantic attributes.

Reconciled against the 25 categories present in HouseExpo. Keys match the
dataset exactly; check_keys() should report no missing and no extra.

PROVENANCE
----------
Drafted with AI assistance, then revised by the authors. State this in the
paper. The lexicon is ground truth for the grounding predicate, so its
origin is a methodological fact, not a footnote.

Attributes were NOT generated by the same model family that answers
benchmark queries. Doing so would leak the evaluated model's vocabulary
into the ground truth and inflate grounding scores.

DESIGN RULES (keep these when you revise)
-----------------------------------------
1. Attributes are what an OPERATOR would type when annotating, or what a
   USER would say when asking. Not dictionary synonyms of the label.
   Kitchen gets "cooking", "meals", "food" because people ask for "where
   people eat", not because those words define a kitchen.

2. Prefer single content words. Multi-word attributes rarely help the
   lexical matcher and inflate token counts.

3. Do NOT include ordinal or quantity words ("second", "main", "north").
   The near-miss ungroundable stratum uses exactly those ("the second
   kitchen"), and including them would make those queries falsely ground.

4. Do NOT repeat the label itself or its stem. The label is matched
   separately; duplicating it in attributes inflates grounding scores
   without adding reach. This is why "Hallway" has no "hallway" attribute.

5. Some overlap between categories is realistic and correct. Bedroom and
   Guest_Room both involve sleeping; both elevators are elevators. Overlap
   is a problem only when it makes a benchmark query ambiguous, which
   benchmark.py must detect and reject at generation time. Do not
   artificially separate genuinely overlapping concepts.

6. Watch prefix collisions. verify.py stems by 3-character prefix, so
   "bat" matches bathroom, bathtub AND battery. Run check_collisions()
   after every edit and justify anything it reports.

CHANGES FROM DRAFT
------------------
- Removed 7 categories absent from this dataset: Recreation_Room,
  Hobby_Room, Healthcare_Lab, Stairwell, Laundry, Basement, Garden.
- Added Hall, Passenger_elevator, Room.
- Resolved harmful prefix collisions by removing: Kitchen "stove" (collided
  with Storage), Bedroom "rest" (collided with Toilet "restroom"), Office
  "staff" (collided with stairs vocabulary), Wardrobe "garments" (collided
  with Garden), Freight_elevator "cargo" (collided with Garage "car"),
  Balcony "fresh air" (collided with "freight").
- Room left deliberately empty; see NON_TARGET_CATEGORIES.
"""

LEXICON: dict[str, list[str]] = {
    # --- living and social ---
    "Living_Room": [
        "lounge", "sitting", "relaxing", "sofa", "television", "social",
    ],
    "Dining_Room": [
        "dining", "eating", "meals", "supper", "dinner",
    ],
    "Kitchen": [
        "cooking", "food", "meals", "eating", "fridge", "pantry",
    ],
    "Gym": [
        "exercise", "fitness", "workout", "training", "weights",
    ],

    # --- sleeping ---
    "Bedroom": [
        "sleeping", "bed", "night", "slumber",
    ],
    "Child_Room": [
        "child", "kids", "nursery", "playing", "sleeping", "bed",
    ],
    "Guest_Room": [
        "guest", "visitor", "spare", "sleeping", "bed",
    ],

    # --- sanitation ---
    "Bathroom": [
        "washing", "shower", "bathing", "sink", "hygiene",
    ],
    "Toilet": [
        "restroom", "washroom", "lavatory", "hygiene",
    ],

    # --- work ---
    "Office": [
        "work", "desk", "study", "computer", "paperwork",
    ],

    # --- circulation ---
    # NOTE: "Hall" and "Hallway" both stem to 'hal' at prefix length 3.
    # Neither carries its own name as an attribute, so direct queries are
    # resolved by exact label and attributes provide non-overlapping reach.
    # Confirm what SUNCG means by "Hall" in your data; if it is merely a
    # synonym for Hallway, merge the two in the loader instead.
    "Hall": [
        "atrium", "concourse", "gathering", "open",
    ],
    "Hallway": [
        "corridor", "passage", "walkway", "circulation",
    ],
    "Lobby": [
        "entrance", "reception", "waiting", "foyer", "arrival",
    ],
    "Entryway": [
        "entrance", "doorway", "arrival", "porch", "vestibule",
    ],

    # --- vertical transport ---
    # These deliberately share "elevator" and "lift". A plan containing both
    # makes any query for "the elevator" ambiguous, and benchmark.py must
    # reject such queries rather than pick one.
    "Passenger_elevator": [
        "elevator", "lift", "passenger", "vertical",
    ],
    "Freight_elevator": [
        "elevator", "lift", "freight", "goods", "hoist",
    ],

    # --- storage and service ---
    "Storage": [
        "storage", "supplies", "stock", "keeping",
    ],
    "Wardrobe": [
        "clothes", "closet", "hanging", "dressing",
    ],
    "Garage": [
        "vehicle", "car", "parking", "tools",
    ],
    "Boiler_room": [
        "boiler", "heating", "plant", "utilities", "mechanical",
    ],
    "Aeration": [
        "ventilation", "shaft", "airflow", "duct",
    ],

    # --- outdoor and semi-outdoor ---
    "Balcony": [
        "balcony", "outdoor", "railing", "overlook",
    ],
    "Terrace": [
        "terrace", "outdoor", "patio", "paved",
    ],
    "Loggia": [
        "loggia", "veranda", "covered", "outdoor",
    ],

    # --- generic ---
    # Deliberately empty. "Room" is an unlabelled space in SUNCG: a real
    # physical area and a valid waypoint, but not something anyone asks for
    # by name. Empty attributes mean nothing grounds to it, and
    # NON_TARGET_CATEGORIES keeps it out of benchmark target selection.
    "Room": [],
}

# Valid graph nodes, never valid query targets. benchmark.py must exclude
# these when choosing expected answers, for every stratum including the
# anchor of a relational query.
NON_TARGET_CATEGORIES: set[str] = {"Room"}

# Categories that are circulation rather than destinations. The loader
# should type these as 'corridor', not 'room', so that relational queries
# such as "the room next to X" do not resolve to connective space.
CIRCULATION_CATEGORIES: set[str] = {"Hallway", "Hall"}

# Categories that are vertical transport. Typed as 'waypoint' by the loader.
# Retained in the graph because multi-floor work in later phases needs them.
TRANSPORT_CATEGORIES: set[str] = {"Passenger_elevator", "Freight_elevator"}

# Used only if a category appears that is not in LEXICON. With the keys
# reconciled this should never fire; if it does, the dataset changed.
FALLBACK: list[str] = ["room", "space", "area"]


def attributes_for(category: str) -> list[str]:
    """Attributes for a category, falling back for unmapped ones."""
    return LEXICON.get(category, FALLBACK)


def is_valid_target(category: str) -> bool:
    """Whether a node of this category may be a benchmark query answer."""
    return category not in NON_TARGET_CATEGORIES


def check_keys(dataset_categories: list[str]) -> None:
    """Reconcile this lexicon against the categories actually in the data."""
    have = set(LEXICON)
    want = set(dataset_categories)
    missing = sorted(want - have)
    extra = sorted(have - want)

    print(f"dataset categories : {len(want)}")
    print(f"lexicon keys       : {len(have)}")
    print(f"matched            : {len(have & want)}")

    if missing:
        print(f"\nMISSING from lexicon ({len(missing)}) -- will use FALLBACK:")
        for c in missing:
            print(f"  {c}")
    if extra:
        print(f"\nEXTRA in lexicon ({len(extra)}) -- safe to delete:")
        for c in extra:
            print(f"  {c}")
    if not missing and not extra:
        print("\nkeys reconcile exactly")


def check_collisions(min_prefix: int = 3) -> None:
    """
    Report attributes colliding under the verifier's prefix stemming.
    Cross-category collisions are not automatically wrong, but each one
    should be a deliberate choice. Justify every survivor in a comment.
    """
    from collections import defaultdict

    by_stem: dict[str, set[str]] = defaultdict(set)
    for category, attrs in LEXICON.items():
        for attr in attrs:
            for word in attr.lower().split():
                by_stem[word[:min_prefix]].add(f"{category}:{word}")

    collisions = {
        stem: sorted(entries)
        for stem, entries in by_stem.items()
        if len({e.split(":", 1)[1] for e in entries}) > 1
    }

    if not collisions:
        print(f"no cross-word collisions at prefix length {min_prefix}")
        return

    print(f"collisions at prefix length {min_prefix} "
          f"({len(collisions)} stems):\n")
    for stem, entries in sorted(collisions.items()):
        print(f"  '{stem}' <- {', '.join(entries)}")


if __name__ == "__main__":
    check_collisions()